# Generated by Django 3.1.2 on 2021-02-10 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('name', models.TextField()),
                ('marks', models.ManyToManyField(blank=True, related_name='assessment', to='marks.Mark')),
            ],
        ),
    ]
