# Generated by Django 3.1.2 on 2021-02-10 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('units', '0001_initial'),
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('period', models.TextField()),
                ('icon', models.URLField()),
                ('announcements', models.ManyToManyField(blank=True, related_name='class_announcement', to='announcements.Announcement')),
                ('students', models.ManyToManyField(blank=True, related_name='class_student', to='students.Student')),
                ('teachers', models.ManyToManyField(blank=True, related_name='class_teacher', to='teachers.Teacher')),
                ('units', models.ManyToManyField(blank=True, related_name='class_unit', to='units.Unit')),
            ],
        ),
    ]
