# Generated by Django 3.1.2 on 2021-02-10 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('assessments', models.ManyToManyField(blank=True, related_name='unit', to='assessments.Assessment')),
            ],
        ),
    ]
